eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  rabbitmq:
    host: 192.168.91.1
    port: 5672
    username: rabbitadmin
    password: 123456
  application:
    name: eshop-datasync-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.91.142:3306/eshop?charsetEncoding=utf8
    username: root
    password: root